archive/comments/api/urls.py
from django.conf.urls import url

from .views import (
    CommentListAPIView,
    ParentListAPIView,
    ChildrenListAPIView,
    CommentDetailAPIView,
)

urlpatterns = [
    url(r'^$', CommentListAPIView.as_view(), name="list"),
    url(r'^parent/', ParentListAPIView.as_view(), name="parents"),
    url(r"^child/", ChildrenListAPIView.as_view(), name="children"),
    url(r"^(?P<pk>\d+)/$", CommentDetailAPIView.as_view(), name="detail"),
]

archive/comments/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import CommentThreadView, CommentReplyView, CommentDeleteView

app_name = "comments"

# Commented out the url's leading to function based views
urlpatterns = [
    # url(r"^thread/(?P<content>\w+)/(?P<pk>\d+)", thread, name="thread"),
    url(r"^thread/(?P<content>\w+)/(?P<pk>\d+)/$", CommentThreadView.as_view(), name="thread"),
    # url(r"^reply/(?P<comment>\d+)", reply, name="reply"),
    url(r"^reply/(?P<comment>\d+)/$", CommentReplyView.as_view(), name="reply"),
    url(r"^delete/(?P<comment>\d+)/$", login_required(CommentDeleteView.as_view()), name="delete"),
]

project/blog19/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings

import object_tools

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^post/", include("project.posts.urls", namespace="posts")),
    url(r'^object-tools/', include(object_tools.tools.urls)),
    # url(r'^formfactory/', include("formfactory.urls", namespace="formfactory"))
]

if settings.DEBUG:
    urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings

import object_tools

from archive.posts.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^object-tools/', include(object_tools.tools.urls)),
    # url(r'^formfactory/', include("formfactory.urls", namespace="formfactory")),
    url(r"^post/", include("archive.posts.urls", namespace="posts")),
    url(r"^comment/", include("archive.comments.urls", namespace="comments")),
    url(r"^account/", include("archive.accounts.urls", namespace="accounts")),
    url(r"^api/post/", include("archive.posts.api.urls", namespace="posts-api")),
    url(r"^api/comment/", include("archive.comments.api.urls", namespace="comments-api")),
    url(r"^$", home),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

archive/comments/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.core.urlresolvers import reverse


class CommentManager(models.Manager):
    def filter_parents_by_instance(self, instance, *args, **kwargs):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        object_id = instance.id
        return super(CommentManager, self).filter(content_type=content_type, object_id=object_id).filter(parent__isnull=True)

    def filter_by_instance(self, instance, *args, **kwargs):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        object_id = instance.id
        return super(CommentManager, self).filter(content_type=content_type, object_id=object_id)

    def filter_parents(self):
        return super(CommentManager, self).filter(parent__isnull=True)

    def filter_children(self):
        return super(CommentManager, self).filter(parent__isnull=False)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    parent = models.ForeignKey("self", null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    object_instance = GenericForeignKey("content_type", "object_id")

    objects = CommentManager()

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

    @property
    def children(self):
        if self.is_parent:
            qs = Comment.objects.filter(parent=self)
            return qs
        return None

    def __unicode__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        instance = self.content_type.model_class().objects.get(id=self.object_id).id
        if self.is_parent:
            # return thread
            return reverse("comments:thread", kwargs={"content": "post", "pk": instance})
        # return reply
        return reverse("comments:reply", kwargs={"comment": self.pk})

archive/comments/forms.py
from django import forms


class CreateCommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    parent_id = forms.IntegerField(required=False, widget=forms.HiddenInput)
    comment_body = forms.CharField(label="", widget=forms.Textarea, max_length=200)

archive/comments/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView

from .serializers import ListSerializer, ChildSerializer, DetailSerializer
from ..models import Comment


class CommentListAPIView(ListAPIView):
    serializer_class = ListSerializer

    def get_queryset(self):
        return Comment.objects.all()


class ParentListAPIView(ListAPIView):
    serializer_class = ListSerializer

    def get_queryset(self):
        return Comment.objects.filter_parents()


class ChildrenListAPIView(ListAPIView):
    serializer_class = ChildSerializer

    def get_queryset(self):
        return Comment.objects.filter_children()


class CommentDetailAPIView(RetrieveAPIView):
    serializer_class = DetailSerializer
    queryset = Comment.objects.all()
    lookup_field = "pk"

archive/comments/views.py
import json

from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import TemplateView

from .forms import CreateCommentForm
from .models import Comment
from .utils import make_new_form
# I left the function based views uncommented out, even though they are ot used, for future reference


def reply(request, comment):
    comment = Comment.objects.get(id=int(comment))
    parent = comment

    if comment.parent:
        parent = comment.parent

    form = None

    if request.user.is_authenticated():
        initial = {
            "content_type": comment.content_type,
            "object_id": comment.object_id,
        }
        form = CreateCommentForm(request.POST or None, initial=initial)
        if form.is_valid():
            form_content_type = form.cleaned_data.get("content_type")
            content_type = ContentType.objects.get(model=form_content_type)
            form_object_id = form.cleaned_data.get("object_id")
            form_comment = form.cleaned_data.get("comment_body")
            parent = comment

            comment, created = Comment.objects.get_or_create(
                user=request.user,
                content_type=content_type,
                object_id=form_object_id,
                body=form_comment,
                parent=parent,
            )
            return HttpResponseRedirect(comment.get_absolute_url())

    context = {
        "comment": parent,
        "form": form,
    }
    return render(request, "replies.html", context)


def thread(request, content, pk):
    content_type = ContentType.objects.get(model=content)
    object_id = pk
    instance = content_type.model_class().objects.get(id=int(pk))
    comments = Comment.objects.filter(content_type=content_type, object_id=object_id)
    form = None

    if request.user.is_authenticated():
        initial = {
            "content_type": content_type,
            "object_id": object_id,
        }
        form = CreateCommentForm(request.POST or None, initial=initial)
        if form.is_valid():
            form_content_type = form.cleaned_data.get("content_type")
            content_type = ContentType.objects.get(model=form_content_type)
            form_object_id = form.cleaned_data.get("object_id")
            form_comment = form.cleaned_data.get("comment_body")
            comment_id = str(request.POST.get("comment_id"))
            try:
                comment_instance = Comment.objects.get(id=comment_id)
                parent = comment_instance
            except:
                parent = None

            comment, created = Comment.objects.get_or_create(
                user=request.user,
                content_type=content_type,
                object_id=form_object_id,
                body=form_comment,
                parent=parent,
            )
            return HttpResponseRedirect(comment.get_absolute_url())

    context = {
        "comments": comments,
        "instance": instance,
        "form": form,
    }
    return render(request, "comments.html", context)


class CommentThreadView(TemplateView):
    template_name = "comments.html"
    partial_template = "comments_partial.html"

    def get(self, *args, **kwargs):
        content = kwargs.get("content")
        self.object_id = int(kwargs.get("pk"))
        self.content_type = ContentType.objects.get(model=content)
        self.instance = self.content_type.model_class().objects.get(id=self.object_id)
        self.comments = Comment.objects.filter(content_type=self.content_type, object_id=self.object_id)
        context = self.get_context_data(obj_id=self.object_id, c_type=self.content_type, **kwargs)
        if self.request.is_ajax():
            html = render_to_string("comments_partial.html", context=context, request=self.request)
            serialized_data = json.dumps({"html": html})
            return HttpResponse(serialized_data, content_type="application/json")
        return self.render_to_response(context)

    def post(self, *args, **kwargs):
        form = CreateCommentForm(self.request.POST)
        if form.is_valid():
            form_content_type = form.cleaned_data.get("content_type")
            content_type = ContentType.objects.get(model=form_content_type)
            form_object_id = form.cleaned_data.get("object_id")
            form_comment = form.cleaned_data.get("comment_body")
            comment_id = str(self.request.POST.get("comment_id"))
            try:
                comment_instance = Comment.objects.get(id=comment_id)
                parent = comment_instance
            except:
                parent = None

            comment, created = Comment.objects.get_or_create(
                user=self.request.user,
                content_type=content_type,
                object_id=form_object_id,
                body=form_comment,
                parent=parent,
            )
            if self.request.is_ajax():
                comments = Comment.objects.filter(content_type=content_type, object_id=form_object_id)
                instance = content_type.model_class().objects.get(id=form_object_id)
                new_form = make_new_form(self.request, form_object_id, content_type)
                context = {
                    "form": new_form,
                    "comments": comments,
                    "instance": instance,
                }
                html = render_to_string("comments_partial.html", context=context, request=self.request)
                serialized_data = json.dumps({"html": html})
                return HttpResponse(serialized_data, content_type="application/json")
            return HttpResponseRedirect(comment.get_absolute_url())

    def get_context_data(self, obj_id=None, c_type=None, **kwargs):
        super(CommentThreadView, self).get_context_data(**kwargs)
        form = make_new_form(self.request, obj_id=obj_id, c_type=c_type)
        context = {
            "comments": self.comments,
            "instance": self.instance,
            "form": form,
        }

        return context


class CommentReplyView(TemplateView):
    template_name = "replies.html"
    partial_template = "comments_partial.html"

    def get(self, *args, **kwargs):
        comment = int(kwargs.get("comment"))
        self.comment_instance = Comment.objects.get(id=comment)
        self.parent = self.comment_instance
        if self.comment_instance.parent:
            self.parent = self.comment_instance.parent
        context = self.get_context_data(object_pk=self.comment_instance.object_id, content_type=self.comment_instance.content_type, **kwargs)
        return self.render_to_response(context)

    def post(self, *args, **kwargs):
        form = CreateCommentForm(self.request.POST)
        if form.is_valid():
            form_content_type = form.cleaned_data.get("content_type")
            content_type = ContentType.objects.get(model=form_content_type)
            form_object_id = form.cleaned_data.get("object_id")
            form_comment = form.cleaned_data.get("comment_body")
            comment_id = str(self.request.POST.get("comment_id"))
            try:
                comment_instance = Comment.objects.get(id=comment_id)
                parent = comment_instance
            except:
                parent = None

            comment, created = Comment.objects.get_or_create(
                user=self.request.user,
                content_type=content_type,
                object_id=form_object_id,
                body=form_comment,
                parent=parent,
            )
            if self.request.is_ajax():
                comments = Comment.objects.filter(content_type=content_type, object_id=form_object_id)
                instance = content_type.model_class().objects.get(id=form_object_id)
                new_form = make_new_form(self.request, form_object_id, content_type)
                context = {
                    "form": new_form,
                    "comments": comments,
                    "instance": instance,
                }
                html = render_to_string("comments_partial.html", context=context, request=self.request)
                serialized_data = json.dumps({"html": html})
                return HttpResponse(serialized_data, content_type="application/json")
            return HttpResponseRedirect(comment.get_absolute_url())

    def get_context_data(self, object_pk=None, content_type=None, **kwargs):
        super(CommentReplyView, self).get_context_data(**kwargs)
        form = make_new_form(self.request, object_pk, content_type)
        context = {
            "comment": self.parent,
            "form": form,
        }
        return context


class CommentDeleteView(TemplateView):
    template_name = "comments.html"
    partial_template = "comments_partial.html"

    def get(self, *args, **kwargs):
        comment = int(kwargs.get("comment"))
        comment_instance = get_object_or_404(Comment, id=comment)
        if comment_instance.user != self.request.user:
            response = HttpResponse("<h1>You are not allowed to perform this action</h1>")
            response.status_code = 403
            return response
        obj_id = comment_instance.object_id
        c_type = comment_instance.content_type
        comment_instance.delete()
        context = self.get_context_data(object_pk=obj_id, content_type=c_type, **kwargs)
        context["comments"] = Comment.objects.filter(object_id=obj_id, content_type=c_type)
        context["instance"] = c_type.model_class().objects.get(id=obj_id)
        if self.request.is_ajax():
            html = render_to_string("comments_partial.html", context=context, request=self.request)
            serialized_data = json.dumps({"html": html})
            return HttpResponse(serialized_data, content_type="application/json")

archive/comments/templates/comments.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
    <div id="comments-section">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                {% if form %}
                    <form method="POST" action="{% url 'comments:thread' 'post' instance.id %}" >{% csrf_token %}
                        {{form|crispy}}
                        <input class="btn btn-default" type="submit" value="Add Comment" />
                    </form>
                {% endif %}
                {% if instance.comments %}
                    <div>
                        <br><br>
                        <strong>{{instance.comment_count}} Comments</strong>
                        {% for comment in instance.comments %}
                            <hr >
                            <blockquote>
                                <p>{{comment.body}}</p>
                                <footer>via {{comment.user.username}} | {{comment.date_added|timesince}} ago </footer>
                                {% for child in comment.children %}
                                <blockquote>
                                    <p>{{child.body}}</p>
                                    <footer>via {{child.user.username}} | {{child.date_added|timesince}} ago {% if request.user == child.user %}<a class="delete-comment pull-right" data-href="{% url 'comments:delete' child.id %}" href=""><i class="fa fa-trash-o" aria-hidden="true"></i></a>{% endif %}</footer>
                                </blockquote>
                                {% endfor %}
                            </blockquote>
                            {% if form %}
                                <span class="pull-right"><a href="{% url 'comments:reply' comment.id %}"> View Replies</a> {% if request.user == comment.user %}| &nbsp;<a class="pull-right" href="{% url 'comments:delete' comment.id %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>{% endif %}</span><input type="button" class="reply-textarea-button" value="Add Reply" />
                                <div class="reply-textarea" hidden>
                                    <form method="POST" action="{% url 'comments:thread' 'post' instance.id %}" >{% csrf_token %}
                                        {{form|crispy}}
                                        <input type="hidden" id="comment_id" name="comment_id" value="{{comment.id}}" />
                                        <input class="btn btn-default" type="submit" value="Add Reply" />
                                    </form>
                                </div>
                            {% else %}
                                <div class="pull-left"><a href="{% url 'comments:reply' comment.id %}"> View Replies</a></div>
                                <br>
                            {% endif %}
                            <hr >
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

archive/comments/templates/comments_partial.html
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            {% if form %}
                <form method="POST" action="" >{% csrf_token %}
                    {{form|crispy}}
                    <input id="post-comment" post-url="{% url 'comments:thread' 'post' instance.id %}" class="btn btn-default" type="submit" value="Add Comment" />
                </form>
            {% endif %}
            {% if instance.comments %}
                <div>
                    <br><br>
                    <strong>{{instance.comment_count}} Comments</strong><span class="pull-right"><a href="{% url 'comments:thread' 'post' instance.id %}"> View Comments</a></span>
                    {% for comment in instance.comments %}
                        <hr >
                        <blockquote>
                            <p>{{comment.body}}</p>
                            <footer>via {{comment.user.username}} | {{comment.date_added|timesince}} ago </footer>
                            {% for child in comment.children %}
                            <blockquote>
                                <p>{{child.body}}</p>
                                <footer>via {{child.user.username}} | {{child.date_added|timesince}} ago {% if request.user == child.user %}<a class="delete-comment pull-right" data-href="{% url 'comments:delete' child.id %}" href=""><i class="fa fa-trash-o" aria-hidden="true"></i></a>{% endif %}</footer>
                            </blockquote>
                            {% endfor %}
                        </blockquote>
                        {% if form %}
                            <span class="pull-right"><a href="{% url 'comments:reply' comment.id %}"> View Replies</a>{% if request.user == comment.user %} | &nbsp;<a class="delete-comment"  data-href="{% url 'comments:delete' comment.id %}" href=""><i class="fa fa-trash-o" aria-hidden="true"></i></a>{% endif %}</span><input type="button" class="reply-textarea-button" value="Add Reply" />
                            <div class="reply-textarea" hidden>
                                <form method="POST" action="" >{% csrf_token %}
                                    {{form|crispy}}
                                    <input type="hidden" id="comment_id" name="comment_id" value="{{comment.id}}" />
                                    <input class="add-reply-button" data-url="{% url 'comments:thread' 'post' instance.id %}" type="submit" value="Add Reply" />
                                </form>
                            </div>
                        {% else %}
                            <div class="pull-left"><a href="{% url 'comments:reply' comment.id %}"> View Replies</a></div>
                            <br>
                        {% endif %}
                        <hr >
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

archive/comments/templates/replies.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
    <div id="comments-section">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div>
                    <hr >
                    <blockquote>
                        <p>{{comment.body}}</p>
                        <footer>via {{comment.user.username}} | {{comment.date_added|timesince}} ago </footer>
                        {% for child in comment.children %}
                        <blockquote>
                            <p>{{child.body}}</p>
                            <footer>via {{child.user.username}} | {{child.date_added|timesince}} ago {% if request.user == child.user %}<a class="pull-right" href="{% url 'comments:delete' child.id %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>{% endif %}</footer>
                        </blockquote>
                        {% endfor %}
                    </blockquote>
                    {% if form %}
                        <input type="button" class="reply-textarea-button" value="Add Reply" />
                        <div class="reply-textarea" hidden>
                            <form method="POST" action="{% url 'comments:thread' 'post' comment.object_id %}" >{% csrf_token %}
                                {{form|crispy}}
                                <input type="hidden" id="comment_id" name="comment_id" value="{{comment.id}}" />
                                <input class="btn btn-default" type="submit" value="Add Reply" />
                            </form>
                        </div>
                    {% endif %}
                    <hr >
                </div>
            </div>
        </div>
    </div>
{% endblock %}