archive/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import LoginView, RegisterView, logout_view

app_name = "accounts"

urlpatterns = [
    url(r"^login/$", LoginView.as_view(), name="login"),
    url(r"^register/$", RegisterView.as_view(), name="register"),
    url(r"^logout/$", login_required(logout_view), name="logout"),
]

archive/comments/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import CommentThreadView, CommentReplyView, CommentDeleteView

app_name = "comments"

# Commented out the url's leading to function based views
urlpatterns = [
    # url(r"^thread/(?P<content>\w+)/(?P<pk>\d+)", thread, name="thread"),
    url(r"^thread/(?P<content>\w+)/(?P<pk>\d+)/$", CommentThreadView.as_view(), name="thread"),
    # url(r"^reply/(?P<comment>\d+)", reply, name="reply"),
    url(r"^reply/(?P<comment>\d+)/$", CommentReplyView.as_view(), name="reply"),
    url(r"^delete/(?P<comment>\d+)/$", login_required(CommentDeleteView.as_view()), name="delete"),
]

archive/posts/api/urls.py
from django.conf.urls import url

from .views import (
    PostListAPIView,
    PostDetailAPIView,
    PostUpdateAPIView,
    PostDeleteAPIView,
    PostCreateAPIView
)

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name="list"),
    url(r'^create/', PostCreateAPIView.as_view(), name="create"),
    url(r"^detail/(?P<slug>(\w+-?)+)$", PostDetailAPIView.as_view(), name="detail"),
    url(r"^update/(?P<pk>\d+)$", PostUpdateAPIView.as_view(), name="update"),
    url(r"^delete/(?P<pk>\d+)$", PostDeleteAPIView.as_view(), name="delete"),
]

project/blog19/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings

import object_tools

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^post/", include("project.posts.urls", namespace="posts")),
    url(r'^object-tools/', include(object_tools.tools.urls)),
    # url(r'^formfactory/', include("formfactory.urls", namespace="formfactory"))
]

if settings.DEBUG:
    urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings

import object_tools

from archive.posts.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^object-tools/', include(object_tools.tools.urls)),
    # url(r'^formfactory/', include("formfactory.urls", namespace="formfactory")),
    url(r"^post/", include("archive.posts.urls", namespace="posts")),
    url(r"^comment/", include("archive.comments.urls", namespace="comments")),
    url(r"^account/", include("archive.accounts.urls", namespace="accounts")),
    url(r"^api/post/", include("archive.posts.api.urls", namespace="posts-api")),
    url(r"^api/comment/", include("archive.comments.api.urls", namespace="comments-api")),
    url(r"^$", home),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

archive/posts/models.py
from __future__ import unicode_literals

import random

from django.db import models
from django.db.models.signals import pre_save
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.utils import timezone, safestring
from django.utils.text import slugify

from markdown_deux import markdown

from archive.comments.models import Comment


def upload_to(instance, filename):
    qs = Post.objects.all()
    instance_id = 1
    if qs.exists():
        instance_id = qs.first().id + 1
    filename = filename.split(".")
    filename = "%s_%s_%s.%s" % (filename[0], instance_id, random.randrange(100), filename[1])
    return filename


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish_on__lte=timezone.now())


class User(AbstractUser):
    pass


class Post(models.Model):
    title = models.CharField(max_length=120)
    body = models.TextField()
    slug = models.SlugField(unique=True)
    image = models.ImageField(null=True, blank=True, upload_to=upload_to, height_field="height", width_field="width")
    height = models.IntegerField(default=0)
    width = models.IntegerField(default=0)
    draft = models.BooleanField(default=False)
    publish_on = models.DateField(auto_now=False, auto_now_add=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    modified = models.DateTimeField(auto_now=True, auto_now_add=False)

    objects = PostManager()

    def __unicode__(self):
        return "%s by %s" % (self.title, self.author)

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"pk": self.pk})

    def get_marked_content(self):
        content = markdown(self.body)
        marked = safestring.mark_safe(content)
        return marked

    @property
    def comments(self):
        qs = Comment.objects.filter_parents_by_instance(self)
        return qs

    @property
    def comment_count(self):
        number = self.comments.count()
        return number

    @property
    def content_type(self):
        c_type = ContentType.objects.get_for_model(self.__class__)
        return c_type

    class Meta:
        ordering = ["-created", "-modified"]


def pre_save_slug_modify(sender, instance, *args, **kwargs):
    if instance.id:
        slug = "%s-%s" % (instance.title, instance.id)
        slug = slugify(slug)
        instance.slug = slug
    else:
        qs = Post.objects.all()
        if qs.exists():
            index = qs.first().id + 1
            slug = "%s-%s" % (instance.title, index)
            slug = slugify(slug)
            instance.slug = slug
        else:
            slug = "%s-1" % instance.title
            slug = slugify(slug)
            instance.slug = slug

pre_save.connect(receiver=pre_save_slug_modify, sender=Post)

archive/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post


class PostCreateForm(forms.ModelForm):
    body = forms.CharField(widget=PagedownWidget(show_preview=False))

    class Meta:
        model = Post
        fields = ["title", "body", "image", "draft", "publish_on", "author"]

archive/posts/api/views.py
from django.db.models import Q
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    RetrieveUpdateAPIView,
    DestroyAPIView,
    CreateAPIView
)
from rest_framework.pagination import LimitOffsetPagination, PageNumberPagination
from rest_framework.permissions import (
    AllowAny,
    IsAdminUser,
    IsAuthenticated,
    IsAuthenticatedOrReadOnly
)

from ..models import Post
from .serializers import PostListSerializer, PostDetailSerializer, PostUpdateCreateSerializer
from .pagination import Paginator
from .permissions import IsOwnerOrSuperUser


class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    permission_classes = [AllowAny, ]
    # unnecessary filters for test reasons
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ["title", "body", "author__username", "author__first_name"]
    # pagination class
    # pagination_class = LimitOffsetPagination
    pagination_class = Paginator

    # ugly search for test reasons
    def get_queryset(self):
        queryset = Post.objects.all()
        search = self.request.GET.get("q")
        if search:
            queryset = Post.objects.all().filter(
                Q(title__icontains=search) |
                Q(body__icontains=search) |
                Q(author__username__icontains=search) |
                Q(author__first_name__icontains=search)
            )
        return queryset


class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = "slug"
    permission_classes = [AllowAny, ]


class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [IsOwnerOrSuperUser, ]


class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostUpdateCreateSerializer
    permission_classes = [IsOwnerOrSuperUser, ]

    def perform_update(self, serializer):
        serializer.save(author=self.request.user)


class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostUpdateCreateSerializer
    permission_classes = [IsAuthenticated, ]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

archive/posts/views.py
from urllib import quote_plus

from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

from .models import Post
from .forms import PostCreateForm
from archive.comments.models import Comment
from archive.comments.forms import CreateCommentForm


# Create your views here.
def home(request):
    queryset_list = Post.objects.active()
    if request.user.is_staff:
        queryset_list = Post.objects.all()
    search = request.GET.get("q")
    if search:
        queryset_list = queryset_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search) |
            Q(author__username__icontains=search)
        ).distinct()
    paginator = Paginator(queryset_list, 10)  # Show 10 posts per page
    page_index = "page"
    page = request.GET.get(page_index)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
        "posts": queryset,
        "page": page_index
    }
    return render(request, "home.html", context)


@login_required()
def create(request):
    if not request.user.is_staff:
        raise Http404
    form = PostCreateForm(files=request.FILES or None)
    context = {
        "form": form
    }

    if request.method == "POST":
        form = PostCreateForm(request.POST, request.FILES)
        context["form"] = form

        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            messages.success(request, "Succesfully created %s" % instance.title)
            return redirect(instance.get_absolute_url())
        else:
            messages.error(request, "Could not create post.")
            return render(request, "create.html", context)

    return render(request, "create.html", context)


def detail(request, pk):
    instance = get_object_or_404(Post, pk=pk)
    content = instance.title
    content = quote_plus(content)
    comments = Comment.objects.filter_by_instance(instance)
    form = None

    if request.user.is_authenticated():
        initial = {
            "content_type": instance.content_type,
            "object_id": instance.id,
        }
        form = CreateCommentForm(request.POST or None, initial=initial)
        if form.is_valid():
            form_content_type = form.cleaned_data.get("content_type")
            content_type = ContentType.objects.get(model=form_content_type)
            form_object_id = form.cleaned_data.get("object_id")
            form_comment = form.cleaned_data.get("comment_body")
            comment_id = str(request.POST.get("comment_id"))
            try:
                comment_instance = Comment.objects.get(id=comment_id)
                parent = comment_instance
            except:
                parent = None

            comment, created = Comment.objects.get_or_create(
                user=request.user,
                content_type=content_type,
                object_id=form_object_id,
                body=form_comment,
                parent=parent,
            )
            return HttpResponseRedirect(comment.get_absolute_url())

    context = {
        "post": instance,
        "url_string": content,
        "comments": comments,
        "form": form,
    }
    return render(request, "detail.html", context)


@login_required()
def update(request, pk):
    instance = get_object_or_404(Post, pk=pk)
    form = PostCreateForm(instance=instance)
    context = {
        "form": form
    }
    if request.method == "POST":
        form = PostCreateForm(request.POST, request.FILES, instance=instance)
        context["form"] = form

        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, "Succesfully updated %s" % instance.title)
            return redirect(instance.get_absolute_url())
        else:
            form = PostCreateForm(instance=instance)
            context["form"] = form
            messages.error(request, "Could not update %s" % instance.title)
            return render(request, "create.html", context)

    return render(request, "update.html", context)


@login_required()
def delete(request, pk):
    if not request.user.is_staff:
        raise Http404
    instance = get_object_or_404(Post, pk=pk)
    title = instance.title
    instance.delete()
    messages.success(request, "Successfully deleted %s" % title)
    return redirect(reverse("posts:home"))

archive/posts/templates/posts/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

        <title>{% block title %}Ubuzulu{% endblock%}</title>

        {% include "includes/stylesheets.html" %}

        <style>
            {% block style %}
            {% endblock %}
        </style>
        {% block form %}
        {% endblock %}
    </head>

    <body>
        <div id="fb-root"></div>
            <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
                fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
            </script>

    <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                  <a class="navbar-brand" href="{% url 'posts:home' %}">Ubuzulu</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        {% block home_active %}<li><a href="{% url 'posts:home' %}">Home</a></li>{% endblock %}
                        {% block about_active %}<li><a href="#">About</a></li>{% endblock %}
                        {% block callback_active %}<li><a href="#">Callback</a></li>{% endblock %}
                        {% if not request.user.is_authenticated %}
                            {% block register_active %}<li><a href="#">Register</a></li>{% endblock %}
                        {% endif %}
                        <!--<li class="dropdown">-->
                            <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
                            <!--<ul class="dropdown-menu">-->
                                <!--<li><a href="#">Action</a></li>-->
                                <!--<li><a href="#">Another action</a></li>-->
                                <!--<li><a href="#">Something else here</a></li>-->
                                <!--<li role="separator" class="divider"></li>-->
                                <!--<li class="dropdown-header">Nav header</li>-->
                                <!--<li><a href="#">Separated link</a></li>-->
                                <!--<li><a href="#">One more separated link</a></li>-->
                            <!--</ul>-->
                        <!--</li>-->
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}">Login</a></li>
                            <li><a href="{% url 'accounts:register' %}">Register</a></li>
                        {% endif %}
                    </ul>
                    {% if not request.user.is_authenticated and not "/account/login" in request.get_full_path %}
                        <form class="navbar-form navbar-right" method="POST" action="{% url 'accounts:login' %}">
                            {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" class="form-control" name="username" placeholder="username">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control" name="password" placeholder="password">
                                </div>
                                <button type="submit" class="btn btn-default">Login</button>
                        </form>
                    {% endif %}
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container-fluid">
            {% block content %}
            {% endblock %}
        </div>
        {% include "includes/javascript.html" %}
    </body>
    </html>

archive/posts/templates/posts/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block form %}
    {{form.media}}
{% endblock %}

{% block content %}
    <div class="row"  >
        <div id="preview-container" class="col-sm-6" hidden>
            <input type="button" id="hide-preview" class="btn-primary" value="Hide Preview" />
            <hr >
            <div id="title-preview" ></div>
            <br /><br />
            <div id="content-preview" ></div>
            <br />
            <hr >
        </div>

        <div id="edit-container" class="col-sm-6">
            <input type="button" id="show-preview" class="btn-primary" value="Show Preview" />
            <hr >
            <form method="POST" enctype="multipart/form-data" action="">
                {% csrf_token %}
                    {{form|crispy}}
                <input type="submit" value="Create Post"/>
            </form>
        </div>
    </div>
{% endblock %}

archive/posts/templates/posts/delete.html
{% extends "base.html" %}

{% block content %}
    <h1>
        DELETE
    </h1>
{% endblock %}

archive/posts/templates/posts/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <hr >
            <div class="post-section">
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% if post.image %}
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                            <img src="{{ post.image.url }}" class="img-responsive align-center">
                        </div>
                    </div>
                <hr >
                {% endif %}
                <h3 class="text-center">{{ post.title }} -- {% if post.draft %} <span style="color: red;">DRAFT</span>{% endif %} -- {{ post.publish_on }}</h3>
                    <div class="post-body">{{ post.get_marked_content }}</div>
                    <p>Author: {% if post.author.get_full_name %} {{ post.author.get_full_name }} {% else %} {{ post.author.username }} {% endif %}
                        <a class="pull-right" href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">&nbsp;&nbsp;
                            <i class="fa fa-facebook-official" aria-hidden="true"></i>
                        </a>
                        <a class="pull-right" href="https://twitter.com/home?status={{ url_string }}@mfundontini%20{{ request.build_absolute_uri }}">&nbsp;&nbsp;
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                        <a class="pull-right" href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ url_string }}&source=http://swiftforentrepreneurs.com/">&nbsp;&nbsp;
                            <i class="fa fa-linkedin-square" aria-hidden="true"></i>
                        </a>
                    </p>
                    <a href="{% url 'posts:update' post.id %}">
                        <i class="fa fa-pencil" aria-hidden="true"></i>&nbsp;Edit
                    </a>
                    <a class="pull-right" href="{% url 'posts:delete' post.id %}">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>&nbsp;&nbsp;Delete
                    </a>
            </div>
            <hr/>
            <input id="show-comments" type="button" data-url="{% url 'comments:thread' 'post' post.id %}" class="btn-primary" value="Show Comments" />
            <div id="comments-section">
            </div>
            <hr >

        </div>
    </div>
{% endblock %}

archive/posts/templates/posts/home.html
{% extends "base.html" %}

{% block style %}
    .no-lines
    {
        text-decoration: none;
    }
    a:hover
    {
        text-decoration: none;
    }
{% endblock %}

{% block content %}
<div class="row" xmlns="http://www.w3.org/1999/html">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <h1 class="text-center">
                        Izithakazelo ZesiZulu
                    </h1>
                </div>
            </div>
            <div>
                <a class="no-lines" href="{% url 'posts:create' %}"><span class="lead"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;&nbsp;nawe faka esakho</span></a>
                <br /><br />
                <form method="get"  action="">
                    <div class="input-group" >
                        <input class="form-control" type="text" name="q" placeholder="Search posts" value="{{ request.GET.q }}"/>
                        <span class="input-group-btn "><input class="btn btn-default" type="submit" value="Search" /></span>
                    </div>
                </form>
            </div>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <h1>Nazi Esizaziyo Okwamanje:</h1></br>
            {% if posts %}
                {% for post in posts %}
                    <hr>
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                            <h3 class="text-center"><a class="text-center" href="{% url 'posts:detail' post.id %}"><span class="text-center">{{ post.title }}</span></a>{% if post.draft %} -- <span style="color: red;">DRAFT</span>{% endif %}</h3>
                            <h6 class="text-center">{{ post.created|timesince }} ago</h6>
                        </div>
                    </div>
                    </br>
                        <div class="text-justify" >
                            <div class="home-post-body" >{{ post.get_marked_content|truncatechars_html:150 }}</div>
                        </div>
                        <p>Author: {% if post.author.get_full_name %} {{ post.author.get_full_name }} {% else %} {{ post.author.username }} {% endif %}</p>
                        <a href="{% url 'posts:update' post.id %}"><i class="fa fa-pencil" aria-hidden="true"></i>&nbsp;Edit</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="pull-right" href="{% url 'posts:delete' post.id %}"><i class="fa fa-trash-o" aria-hidden="true"></i>&nbsp;Delete</a>
                    <hr>
                {% endfor %}
                <div class="pagination">
                    <span class="step-links">
                        {% if posts.has_previous %}
                            <a href="?{{ page }}={{ posts.previous_page_number }}&q={{ request.GET.q }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                        </span>

                        {% if posts.has_next %}
                            <a href="?{{ page }}={{ posts.next_page_number }}&q={{ request.GET.q }}">next</a>
                        {% endif %}
                    </span>
                 </div>
            {% else %}
                Asikakabi nalezo okwamanje, awuzame ezinye
            {% endif %}
        </div>
    </div>

{% endblock %}

archive/posts/templates/posts/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block form %}
    {{form.media}}
{% endblock %}

{% block content %}
    <div class="row"  >
        <div id="preview-container" class="col-sm-6" hidden>
            <input type="button" id="hide-preview" class="btn-primary" value="Hide Preview" />
            <hr >
            <div id="title-preview" ></div>
            <br /><br />
            <div id="content-preview" ></div>
            <br />
            <hr >
        </div>

        <div id="edit-container" class="col-sm-6">
            <input type="button" id="show-preview" class="btn-primary" value="Show Preview" />
            <hr >
            <form method="POST" enctype="multipart/form-data" action="">
                {% csrf_token %}
                    {{form|crispy}}
                <input type="submit" value="Update Post"/>
            </form>
        </div>
    </div>
{% endblock %}